# Generated by Django 3.2.15 on 2022-09-22 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_auto_20220920_1025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='min_no_people',
        ),
        migrations.AddField(
            model_name='table',
            name='table_name',
            field=models.CharField(default='New table', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[(0, 'pending'), (1, 'confirmed')], default=0, max_length=10),
        ),
    ]
