# Generated by Django 3.2.15 on 2022-09-22 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_auto_20220922_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[(0, 'pending'), (1, 'confirmed')], default='pending', max_length=10),
        ),
    ]
