# Generated by Django 3.2.15 on 2022-10-03 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0008_alter_customer_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='requested_time',
            field=models.CharField(choices=[('12:30', '12:30'), ('13:00', '13:00'), ('13:30', '13:30'), ('14:00', '14:00'), ('14:30', '14:30'), ('15:00', '15:00'), ('15:30', '15:30'), ('19:00', '19:00'), ('19:30', '19:30'), ('20:00', '20:00'), ('20:30', '20:30'), ('21:00', '21:00'), ('21:30', '21:30'), ('22:00', '22:00'), ('22:30', '22:30')], default='12:00', max_length=10),
        ),
    ]
