# Generated by Django 3.2.15 on 2022-10-04 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0009_alter_reservation_requested_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='customer_id',
        ),
        migrations.AddField(
            model_name='reservation',
            name='customer_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='reservations.customer'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
