# Generated by Django 3.2.15 on 2022-11-07 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0011_alter_reservation_requested_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='customer_name',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='table_id',
            new_name='table',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='requested_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('confirmed', 'confirmed'), ('rejected', 'rejected')], default='pending', max_length=10),
        ),
    ]
