# Generated by Django 3.2.15 on 2022-11-17 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0012_auto_20221107_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='no_of_guests',
            field=models.IntegerField(choices=[(1, '1 person'), (2, '2 people'), (3, '3 people'), (4, '4 people'), (5, '5 people'), (6, '6 people'), (7, '7 people'), (8, '8 people')], default=1),
        ),
    ]
