# Generated by Django 3.2.15 on 2022-09-16 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drinkitems',
            name='drinks_menu_section',
            field=models.IntegerField(choices=[(0, 'Wine'), (1, 'Water/Soft Drinks'), (2, 'Apéritif')], default=0),
        ),
        migrations.AddField(
            model_name='fooditems',
            name='food_menu_section',
            field=models.IntegerField(choices=[(0, 'Lunch'), (1, 'Dinner')], default=1),
        ),
        migrations.AlterField(
            model_name='drinkitems',
            name='allergens',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
