# Generated by Django 3.2.15 on 2022-09-20 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0002_auto_20220916_1147'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DrinkItems',
            new_name='DrinkItem',
        ),
        migrations.RenameModel(
            old_name='FoodItems',
            new_name='FoodItem',
        ),
    ]
