# Generated by Django 3.2.15 on 2022-09-22 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0003_auto_20220920_1025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drinkitem',
            name='allergens',
        ),
    ]
