# Generated by Django 3.2.15 on 2022-11-04 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0004_remove_drinkitem_allergens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drinkitem',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='price',
            field=models.FloatField(),
        ),
    ]
